// Basin navigation water for in-harbour vessels (abras, boats, small yachts).
//
// This is the counterpart to navigationWater.ts. That file describes only the
// DEEP OPEN GULF where big ships sail; this file describes the sheltered coastal
// basins — Dubai Marina, Palm Jumeirah inner lagoon, Dubai Creek, and the
// Business Bay / Dubai Water Canal — where small craft circulate.
//
// Design: a basin is modelled as a CORRIDOR — a centerline polyline plus a
// half-width in metres — clipped to the real water polygon traced in water.ts.
// A point is valid basin navigation water when it is BOTH:
//   1. within `halfWidthMeters` of the basin centerline, AND
//   2. inside the basin's source water polygon from WATER_AREAS (so the corridor
//      never spills onto land even where the centerline runs near a bank).
//
// The corridor model (rather than an inward-inset polygon) is deliberate: the
// Creek and Business Bay water polygons are thin slivers that an inset would
// collapse, and Marina/Palm-lagoon corridors follow the navigable channel rather
// than the whole basin. The basin routes in marineRoutes.ts ARE these
// centerlines, so every routed vessel sits on the corridor spine by construction.
//
// Coordinates are [lng, lat]. Centerlines are derived to sit mid-channel in the
// satellite-traced water polygons of water.ts; refine with the Water Debug Editor.

import { WATER_AREAS, type WaterArea } from "@/lib/water";

// The Dubai Creek water polygon pinches nearly shut around lat 25.227, so the
// creek is modelled as two independent corridors (south of the pinch, north of
// it) rather than one that would have to squeeze through a ~4m gap.
export type BasinId = "marina" | "palm-lagoon" | "creek-south" | "creek-north" | "business-bay";

export type BasinCorridor = {
  id: BasinId;
  name: string;
  /** Id of the source water polygon in water.ts this corridor is clipped to. */
  waterAreaId: string;
  /** Centerline the corridor is built around; also the vessel route spine. */
  centerline: [number, number][];
  /** Half-width of the navigable corridor in metres (full width = 2×). */
  halfWidthMeters: number;
};

const METERS_PER_LATITUDE_DEGREE = 111_320;

// Centerlines run mid-channel through each basin's water polygon (water.ts).
// Half-widths are sized to the basin: wide for the Marina/Palm lagoon, tight for
// the narrow Creek and Business Bay canal.
// All centerlines below were generated by sampling the mid-water line of the
// corresponding water.ts polygon and verified so that every point of the route,
// sampled every 25 m (matching the guard), stays inside the water polygon (and
// outside island holes). Half-widths bound runtime drift, not the trace itself.
export const BASIN_CORRIDORS: BasinCorridor[] = [
  {
    id: "marina",
    name: "Dubai Marina Channel",
    waterAreaId: "marina-channels",
    // Main marina channel (west entrance kink excluded), mid-channel throughout.
    centerline: [
      [55.147, 25.07113],
      [55.146, 25.07138],
      [55.145, 25.07153],
      [55.144, 25.07168],
      [55.143, 25.07178],
      [55.142, 25.07188],
      [55.141, 25.07188],
      [55.14, 25.07188],
      [55.139, 25.07188],
      [55.138, 25.07183],
      [55.137, 25.07173],
      [55.136, 25.07158],
      [55.135, 25.07143],
      [55.134, 25.07123],
      [55.133, 25.07098],
      [55.132, 25.07068],
      [55.131, 25.07038],
      [55.13, 25.07003],
      [55.129, 25.06968],
      [55.128, 25.06928],
    ],
    halfWidthMeters: 35,
  },
  {
    id: "palm-lagoon",
    name: "Palm Jumeirah Inner Lagoon",
    waterAreaId: "palm-inner-lagoons",
    // A gentle arc through the lagoon between the crescent and the fronds, kept
    // clear of the trunk/frond comb (the polygon hole).
    centerline: [
      [55.1105, 25.1015],
      [55.115, 25.104],
      [55.121, 25.1055],
      [55.127, 25.106],
      [55.1305, 25.1055],
      [55.128, 25.1048],
      [55.123, 25.1045],
      [55.1175, 25.1042],
      [55.113, 25.1028],
    ],
    halfWidthMeters: 60,
  },
  {
    id: "creek-south",
    name: "Dubai Creek (South)",
    waterAreaId: "dubai-creek",
    // Southern estuary segment, below the ~4 m pinch at lat 25.227.
    centerline: [
      [55.33834, 25.215],
      [55.33816, 25.2165],
      [55.338, 25.218],
      [55.33777, 25.2195],
      [55.33753, 25.221],
      [55.33726, 25.2225],
      [55.33695, 25.224],
    ],
    halfWidthMeters: 20,
  },
  {
    id: "creek-north",
    name: "Dubai Creek (North)",
    waterAreaId: "dubai-creek",
    // Northern estuary segment, above the pinch, running up toward the mouth.
    centerline: [
      [55.3356, 25.2295],
      [55.33516, 25.231],
      [55.33473, 25.2325],
      [55.33422, 25.234],
      [55.33369, 25.2355],
      [55.33314, 25.237],
      [55.33255, 25.2385],
      [55.33192, 25.24],
      [55.33126, 25.2415],
      [55.33057, 25.243],
      [55.32985, 25.2445],
    ],
    halfWidthMeters: 20,
  },
  {
    id: "business-bay",
    name: "Dubai Water Canal & Business Bay",
    waterAreaId: "business-bay-canal",
    // Down the canal loop, mid-water on the traced sliver.
    centerline: [
      [55.26688, 25.1685],
      [55.26643, 25.17],
      [55.26593, 25.1715],
      [55.26603, 25.173],
      [55.26638, 25.1745],
      [55.26673, 25.176],
      [55.26708, 25.1775],
      [55.26765, 25.179],
      [55.26835, 25.1805],
      [55.26905, 25.182],
      [55.26975, 25.1835],
      [55.2708, 25.185],
      [55.27203, 25.1865],
    ],
    halfWidthMeters: 22,
  },
];

// --- geometry helpers -------------------------------------------------------
function pointInRing(point: [number, number], ring: [number, number][]) {
  const [x, y] = point;
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    const intersects = yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi;
    if (intersects) inside = !inside;
  }
  return inside;
}

function distanceToSegmentMeters(
  point: [number, number],
  start: [number, number],
  end: [number, number],
) {
  const meanLatitude = ((point[1] + start[1] + end[1]) * Math.PI) / 540;
  const lngScale = METERS_PER_LATITUDE_DEGREE * Math.cos(meanLatitude);
  const px = (point[0] - start[0]) * lngScale;
  const py = (point[1] - start[1]) * METERS_PER_LATITUDE_DEGREE;
  const ex = (end[0] - start[0]) * lngScale;
  const ey = (end[1] - start[1]) * METERS_PER_LATITUDE_DEGREE;
  const lengthSquared = ex * ex + ey * ey;
  const t = lengthSquared === 0 ? 0 : Math.max(0, Math.min(1, (px * ex + py * ey) / lengthSquared));
  return Math.hypot(px - ex * t, py - ey * t);
}

function distanceToPolylineMeters(point: [number, number], line: [number, number][]) {
  let nearest = Number.POSITIVE_INFINITY;
  for (let i = 1; i < line.length; i++) {
    nearest = Math.min(nearest, distanceToSegmentMeters(point, line[i - 1], line[i]));
  }
  return nearest;
}

const waterAreaById = new Map<string, WaterArea>(WATER_AREAS.map((area) => [area.id, area]));

/** True when the point sits inside the given basin's source water polygon. */
function isInsideBasinWater(point: [number, number], corridor: BasinCorridor) {
  const area = waterAreaById.get(corridor.waterAreaId);
  if (!area) return false;
  if (!pointInRing(point, area.polygon)) return false;
  // Reject anything inside a hole (island/land punched out of the basin).
  for (const hole of area.holes ?? []) {
    if (pointInRing(point, hole)) return false;
  }
  return true;
}

/**
 * True when the point is safe basin navigation water: within the corridor of at
 * least one basin AND inside that basin's water polygon.
 */
export function isPointInAnyBasinNavigationWater(point: [number, number]) {
  return BASIN_CORRIDORS.some(
    (corridor) =>
      distanceToPolylineMeters(point, corridor.centerline) <= corridor.halfWidthMeters &&
      isInsideBasinWater(point, corridor),
  );
}

/** The basin whose corridor the point falls in, if any (nearest centerline). */
export function basinForPoint(point: [number, number]): BasinCorridor | undefined {
  let best: BasinCorridor | undefined;
  let bestDistance = Number.POSITIVE_INFINITY;
  for (const corridor of BASIN_CORRIDORS) {
    const distance = distanceToPolylineMeters(point, corridor.centerline);
    if (
      distance <= corridor.halfWidthMeters &&
      distance < bestDistance &&
      isInsideBasinWater(point, corridor)
    ) {
      best = corridor;
      bestDistance = distance;
    }
  }
  return best;
}

/** Corridor outline rings (for the navigation debug overlay), one per basin. */
export function basinCorridorRing(corridor: BasinCorridor): [number, number][] {
  // Build a simple buffered ribbon: offset each centerline vertex left/right by
  // the half-width along the local normal, then walk down one side and back the
  // other to close the ring. Good enough for a debug outline.
  const left: [number, number][] = [];
  const right: [number, number][] = [];
  const line = corridor.centerline;
  for (let i = 0; i < line.length; i++) {
    const prev = line[Math.max(0, i - 1)];
    const next = line[Math.min(line.length - 1, i + 1)];
    const meanLat = (line[i][1] * Math.PI) / 180;
    const lngScale = METERS_PER_LATITUDE_DEGREE * Math.cos(meanLat);
    const dx = (next[0] - prev[0]) * lngScale;
    const dy = (next[1] - prev[1]) * METERS_PER_LATITUDE_DEGREE;
    const len = Math.hypot(dx, dy) || 1;
    // Normal (perpendicular) unit vector in metres, converted back to degrees.
    const nx = (-dy / len) * (corridor.halfWidthMeters / lngScale);
    const ny = (dx / len) * (corridor.halfWidthMeters / METERS_PER_LATITUDE_DEGREE);
    left.push([line[i][0] + nx, line[i][1] + ny]);
    right.push([line[i][0] - nx, line[i][1] - ny]);
  }
  return [...left, ...right.reverse(), left[0]];
}
