-- Dubai hospitals, generated by scripts/generate-hospitals.ts from OpenStreetMap (ODbL).
-- Regenerate with: npm run generate:hospitals
-- Replaces the hospitals table only; tourism/schools rows are untouched.
BEGIN;
TRUNCATE TABLE public.hospitals;
INSERT INTO public.hospitals (name, lat, lng, images) VALUES
  ('Al Jalila Children''s Hospital', 25.225541, 55.318915, '{}'),
  ('Al Kuwait Hospital', 25.282486, 55.318894, '{}'),
  ('Al Maktoum Hospital', 25.270347, 55.314549, '{}'),
  ('Al Zahra Hospital', 25.105510, 55.180494, '{}'),
  ('American Hospital', 25.235547, 55.313081, '{}'),
  ('Aster Hospital', 25.252577, 55.288902, '{}'),
  ('Barraquer Eye Hospital', 25.209863, 55.320324, '{}'),
  ('Belhoul European Hospital', 25.236913, 55.275257, '{}'),
  ('Belhoul Speciality Hospital', 25.280387, 55.313113, '{}'),
  ('Bella Roma Specialty Hospital', 25.157806, 55.218666, '{}'),
  ('Canadian Specialist Hospital', 25.277364, 55.348399, '{}'),
  ('Cedars Jebel Ali Free Hospital', 25.015572, 55.086936, '{}'),
  ('Dubai Hospital', 25.284803, 55.321549, '{}'),
  ('Emirate Hospital', 25.196768, 55.237213, '{}'),
  ('Emirates Hospital', 25.085336, 55.141799, '{}'),
  ('Emirates Speciality Hospital', 25.232021, 55.317753, '{}'),
  ('Fakeeh University Hospital', 25.121654, 55.387247, '{}'),
  ('GMC Hospital', 25.281319, 55.365005, '{}'),
  ('International Modern Hospital', 25.248884, 55.283371, '{}'),
  ('Iranian Hospital Dubai', 25.230276, 55.269416, '{}'),
  ('Kings Hospital', 25.112508, 55.254557, '{}'),
  ('Latifa Hospital Women and Children', 25.222656, 55.318409, '{}'),
  ('Lifeline Hospital', 25.029261, 55.114703, '{}'),
  ('MedCare Hospital', 25.183308, 55.242700, '{}'),
  ('Medcare Orthopaedics & Spine Hospital', 25.179174, 55.247307, '{}'),
  ('Medeor 24x7 Hospital', 25.257415, 55.306581, '{}'),
  ('Neuro Spinal Hospital', 25.197210, 55.237718, '{}'),
  ('NMC hospital DIP', 25.002922, 55.153739, '{}'),
  ('Quttainah Specialized Hospital', 25.139994, 55.203698, '{}'),
  ('Rashid Hospital', 25.244184, 55.318893, '{}'),
  ('Saudi German Hospital', 25.097170, 55.183819, '{}'),
  ('Shifa International Hospitals DWC', 24.908941, 55.118548, '{}'),
  ('Welcare Hospital', 25.101339, 55.160868, '{}'),
  ('Zulekha Hospital, Dubai', 25.291399, 55.384095, '{}');
COMMIT;
