import { StyleSheet } from "@react-pdf/renderer";

export const offerColors = {
  navy: "#07182f",
  navySoft: "#102a4b",
  gold: "#c9a84c",
  cream: "#f8f5ed",
  ink: "#13223b",
  muted: "#667085",
  line: "#d9dee7",
  pale: "#f3f5f8",
  teal: "#2f8f9d",
};

export const offerStyles = StyleSheet.create({
  page: {
    backgroundColor: "#ffffff",
    color: offerColors.ink,
    fontFamily: "Helvetica",
    paddingBottom: 35,
  },
  header: {
    backgroundColor: offerColors.navy,
    color: "#f8fafc",
    padding: 16,
    minHeight: 122,
    position: "relative",
  },
  headerImage: {
    position: "absolute",
    right: 0,
    top: 0,
    width: "66.667%",
    height: "100%",
    objectFit: "cover",
    opacity: 1,
  },
  headerShade: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "33.333%",
    height: "100%",
    backgroundColor: offerColors.navy,
    opacity: 1,
  },
  headerContent: {
    position: "relative",
    zIndex: 1,
    width: "31%",
  },
  logo: {
    width: 29,
    height: 29,
    objectFit: "contain",
    marginBottom: 4,
  },
  developer: {
    color: "#ffffff",
    fontSize: 8,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  eyebrow: {
    color: offerColors.gold,
    fontSize: 8,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  title: {
    color: "#ffffff",
    fontSize: 25,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1,
    marginBottom: 2,
  },
  subtitle: {
    color: offerColors.gold,
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  projectName: {
    color: offerColors.gold,
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginTop: 8,
    maxWidth: "94%",
  },
  location: {
    color: "#ffffff",
    fontSize: 8,
    marginTop: 3,
  },
  offerMeta: {
    position: "absolute",
    zIndex: 2,
    right: 16,
    top: 14,
    width: 133,
    borderWidth: 1,
    borderColor: offerColors.gold,
    borderRadius: 7,
    padding: 8,
    backgroundColor: "#081b35",
  },
  metaLabel: {
    color: offerColors.gold,
    fontSize: 6,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 1,
  },
  metaValue: {
    color: offerColors.cream,
    fontSize: 8,
    marginBottom: 5,
  },
  body: {
    paddingHorizontal: 21,
    paddingTop: 10,
  },
  oneBody: {
    paddingHorizontal: 14,
    paddingTop: 7,
  },
  oneColumns: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 6,
  },
  oneLeftColumn: { width: "22%" },
  oneCenterColumn: { width: "45%" },
  oneRightColumn: { width: "33%" },
  oneBottomRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 2,
  },
  oneFloorPlanBlock: {
    width: "62%",
    borderWidth: 1,
    borderColor: offerColors.line,
    borderRadius: 5,
    padding: 5,
    backgroundColor: offerColors.pale,
  },
  oneContactBlock: {
    width: "38%",
    marginTop: 0,
    padding: 6,
  },
  oneDetailCard: {
    borderWidth: 1,
    borderColor: offerColors.line,
    borderRadius: 5,
    padding: 5,
    backgroundColor: offerColors.pale,
  },
  oneProjectDetailImage: {
    width: "100%",
    height: 45,
    objectFit: "cover",
    borderRadius: 3,
    marginBottom: 3,
  },
  oneImageCaption: {
    color: offerColors.muted,
    fontSize: 5,
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  oneDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 4,
    paddingVertical: 2,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e6ed",
  },
  oneDetailLabel: { color: offerColors.muted, fontSize: 5.2, textTransform: "uppercase", letterSpacing: 0.2 },
  oneDetailValue: { color: offerColors.ink, fontSize: 6.2, fontFamily: "Helvetica-Bold", textAlign: "right", maxWidth: "63%" },
  oneOverview: { color: "#344054", fontSize: 5.9, lineHeight: 1.3 },
  oneOverviewTitle: { marginTop: 5 },
  onePlanHighlight: { borderRadius: 5, padding: 6, marginTop: 5 },
  onePlanLabel: { fontSize: 5, textTransform: "uppercase", letterSpacing: 0.45, marginBottom: 2 },
  onePlanName: { color: offerColors.cream, fontSize: 8, fontFamily: "Helvetica-Bold", marginBottom: 3 },
  onePlanMeta: { color: "#c9d3e2", fontSize: 5.5 },
  onePlanTotal: { fontSize: 6.2, fontFamily: "Helvetica-Bold" },
  oneTable: { borderWidth: 1, borderColor: offerColors.line, borderRadius: 5, overflow: "hidden" },
  oneTableHeader: { paddingVertical: 3, paddingHorizontal: 5 },
  oneTableRow: { paddingVertical: 3, paddingHorizontal: 5 },
  oneTableTotal: { paddingVertical: 3.5, paddingHorizontal: 5 },
  oneHeaderText: { fontSize: 5.2, letterSpacing: 0.25, textTransform: "uppercase" },
  oneCellText: { color: offerColors.ink, fontSize: 5.7 },
  oneCellStrong: { color: offerColors.ink, fontSize: 5.7, fontFamily: "Helvetica-Bold" },
  oneDistributionBox: { borderWidth: 1, borderColor: offerColors.line, borderRadius: 5, padding: 5 },
  oneDistributionBar: { height: 7, marginBottom: 4 },
  oneDistributionSegment: { height: 7 },
  oneLegend: { flexDirection: "row", flexWrap: "wrap", gap: 3 },
  oneLegendItem: { flexDirection: "row", alignItems: "center", width: "48%", marginBottom: 2 },
  oneLegendDot: { width: 4, height: 4, borderRadius: 2, marginRight: 3 },
  oneLegendText: { color: offerColors.muted, fontSize: 4.8, maxWidth: "88%" },
  oneTimeline: { borderLeftWidth: 1.5, paddingLeft: 7, marginLeft: 3 },
  oneTimelineItem: { position: "relative", marginBottom: 4, minHeight: 16 },
  oneTimelineDot: { position: "absolute", left: -11, top: 1, width: 5, height: 5, borderRadius: 3, borderWidth: 1.5 },
  oneTimelineDue: { fontSize: 4.8, textTransform: "uppercase", marginBottom: 1 },
  oneTimelineLabel: { color: offerColors.ink, fontSize: 5.6, fontFamily: "Helvetica-Bold" },
  oneTimelineAmount: { color: offerColors.muted, fontSize: 4.9, marginTop: 1 },
  oneFinancialBox: { borderRadius: 5, padding: 6 },
  oneFinancialRow: { paddingVertical: 2 },
  oneFinancialLabel: { color: "#c9d3e2", fontSize: 5.3 },
  oneFinancialValue: { color: offerColors.cream, fontSize: 5.3, fontFamily: "Helvetica-Bold" },
  oneFinancialTotal: { paddingTop: 4, marginTop: 1 },
  oneFinancialTotalLabel: { fontSize: 5.5, fontFamily: "Helvetica-Bold", textTransform: "uppercase" },
  oneFinancialTotalValue: { color: offerColors.cream, fontSize: 7.5, fontFamily: "Helvetica-Bold" },
  oneUnitPlanImage: { width: "100%", height: 69, objectFit: "contain", backgroundColor: "#ffffff", borderRadius: 3 },
  oneUnitPhotoImage: { width: "100%", height: 69, objectFit: "cover", backgroundColor: "#e9edf2", borderRadius: 3 },
  oneUnitPlanHeading: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", marginBottom: 3 },
  oneUnitPlanMeta: { color: offerColors.muted, fontSize: 5, textTransform: "uppercase", letterSpacing: 0.25 },
  cardRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    marginBottom: 8,
  },
  summaryCard: {
    width: "32.2%",
    minHeight: 44,
    padding: 6,
    borderRadius: 6,
    backgroundColor: offerColors.navy,
    color: offerColors.cream,
  },
  summaryLabel: {
    color: "#c9d3e2",
    fontSize: 6,
    letterSpacing: 0.45,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  summaryPercent: {
    color: offerColors.gold,
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
  },
  summaryAmount: {
    color: offerColors.cream,
    fontSize: 7,
    marginTop: 1,
  },
  columns: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 8,
  },
  columnsCompact: {
    flexDirection: "row",
    gap: 12,
    marginTop: 11,
    marginBottom: 9,
  },
  leftColumn: {
    width: "42%",
  },
  rightColumn: {
    width: "58%",
  },
  sectionTitle: {
    color: offerColors.navy,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  sectionRule: {
    borderBottomWidth: 1,
    borderBottomColor: offerColors.gold,
    width: 28,
    marginBottom: 6,
  },
  detailCard: {
    borderWidth: 1,
    borderColor: offerColors.line,
    borderRadius: 6,
    padding: 7,
    backgroundColor: offerColors.pale,
  },
  projectDetailImage: {
    width: "100%",
    height: 64,
    objectFit: "cover",
    borderRadius: 4,
    marginBottom: 4,
  },
  unitPlanImage: {
    width: "100%",
    height: 70,
    objectFit: "contain",
    backgroundColor: "#ffffff",
    borderRadius: 4,
  },
  unitPlanSection: {
    borderWidth: 1,
    borderColor: offerColors.line,
    borderRadius: 6,
    padding: 7,
    backgroundColor: offerColors.pale,
    marginTop: 3,
  },
  unitPlanHeading: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  unitPlanMeta: {
    color: offerColors.muted,
    fontSize: 6.5,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  imageCaption: {
    color: offerColors.muted,
    fontSize: 6,
    textTransform: "uppercase",
    letterSpacing: 0.45,
    marginBottom: 4,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 7,
    paddingVertical: 3,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e6ed",
  },
  detailLabel: {
    color: offerColors.muted,
    fontSize: 6.5,
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  detailValue: {
    color: offerColors.ink,
    fontSize: 7.5,
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
    maxWidth: "64%",
  },
  overview: {
    color: "#344054",
    fontSize: 7.5,
    lineHeight: 1.4,
  },
  planHighlight: {
    backgroundColor: offerColors.navy,
    borderRadius: 6,
    padding: 9,
    marginTop: 10,
  },
  planHighlightLabel: {
    color: offerColors.gold,
    fontSize: 6,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginBottom: 4,
  },
  planHighlightName: {
    color: offerColors.cream,
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
  },
  planHighlightRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  planHighlightMeta: { color: "#c9d3e2", fontSize: 7 },
  planHighlightTotal: { color: offerColors.gold, fontSize: 8, fontFamily: "Helvetica-Bold" },
  pageOneNote: {
    borderLeftWidth: 3,
    borderLeftColor: offerColors.gold,
    paddingLeft: 8,
    marginTop: 4,
  },
  pageOneNoteLabel: {
    color: offerColors.navy,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  pageOneNoteText: { color: offerColors.muted, fontSize: 7, marginTop: 2 },
  pageHeading: {
    color: offerColors.navy,
    fontSize: 19,
    fontFamily: "Helvetica-Bold",
    marginBottom: 3,
  },
  pageIntro: { color: offerColors.muted, fontSize: 7.5, marginBottom: 12 },
  table: {
    borderWidth: 1,
    borderColor: offerColors.line,
    borderRadius: 6,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: offerColors.navy,
    color: offerColors.cream,
    paddingVertical: 5,
    paddingHorizontal: 7,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 7,
    borderBottomWidth: 1,
    borderBottomColor: "#e8ebf0",
  },
  tableTotal: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingHorizontal: 7,
    backgroundColor: "#edf1f5",
  },
  colStage: { width: "39%" },
  colPercent: { width: "16%", textAlign: "right" },
  colAmount: { width: "23%", textAlign: "right" },
  colDue: { width: "22%", textAlign: "right" },
  headerText: {
    fontSize: 6.5,
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  cellText: { color: offerColors.ink, fontSize: 7 },
  cellStrong: { color: offerColors.ink, fontSize: 7, fontFamily: "Helvetica-Bold" },
  distributionBox: {
    borderWidth: 1,
    borderColor: offerColors.line,
    borderRadius: 6,
    padding: 8,
  },
  distributionBar: {
    flexDirection: "row",
    height: 10,
    borderRadius: 5,
    overflow: "hidden",
    marginBottom: 7,
  },
  distributionSegment: { height: 10 },
  legend: { flexDirection: "row", flexWrap: "wrap", gap: 5 },
  legendItem: { flexDirection: "row", alignItems: "center", width: "47%", marginBottom: 3 },
  legendDot: { width: 5, height: 5, borderRadius: 3, marginRight: 4 },
  legendText: { color: offerColors.muted, fontSize: 6.2, maxWidth: "88%" },
  timeline: {
    borderLeftWidth: 2,
    borderLeftColor: offerColors.gold,
    paddingLeft: 10,
    marginLeft: 4,
  },
  timelineItem: { position: "relative", marginBottom: 7, minHeight: 21 },
  timelineDot: {
    position: "absolute",
    left: -15,
    top: 1,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: offerColors.navy,
    borderWidth: 2,
    borderColor: offerColors.gold,
  },
  timelineDue: { color: offerColors.gold, fontSize: 6, textTransform: "uppercase", marginBottom: 1 },
  timelineLabel: { color: offerColors.ink, fontSize: 7, fontFamily: "Helvetica-Bold" },
  timelineAmount: { color: offerColors.muted, fontSize: 6.2, marginTop: 1 },
  financialBox: { backgroundColor: offerColors.navy, borderRadius: 6, color: offerColors.cream, padding: 9 },
  financialRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    borderBottomWidth: 1,
    borderBottomColor: "#284365",
  },
  financialLabel: { color: "#c9d3e2", fontSize: 7 },
  financialValue: { color: offerColors.cream, fontSize: 7, fontFamily: "Helvetica-Bold" },
  financialTotal: { flexDirection: "row", justifyContent: "space-between", paddingTop: 6, marginTop: 2 },
  financialTotalLabel: { color: offerColors.gold, fontSize: 7.5, fontFamily: "Helvetica-Bold", textTransform: "uppercase" },
  financialTotalValue: { color: offerColors.cream, fontSize: 10, fontFamily: "Helvetica-Bold" },
  contactBox: {
    marginTop: 9,
    backgroundColor: offerColors.navy,
    borderRadius: 6,
    padding: 9,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  contactCopy: { flexGrow: 1 },
  contactTitle: { color: offerColors.gold, fontSize: 7, letterSpacing: 0.8, textTransform: "uppercase", marginBottom: 3 },
  contactName: { color: offerColors.cream, fontSize: 10, fontFamily: "Helvetica-Bold", marginBottom: 3 },
  contactLine: { color: "#dce6f2", fontSize: 6.5, marginTop: 1 },
  qr: { width: 62, height: 62, backgroundColor: "#ffffff", padding: 3 },
  footer: {
    position: "absolute",
    left: 21,
    right: 21,
    bottom: 12,
    borderTopWidth: 1,
    borderTopColor: offerColors.line,
    paddingTop: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 14,
  },
  disclaimer: { color: offerColors.muted, fontSize: 5.7, lineHeight: 1.2, width: "76%" },
  footerBrand: { color: offerColors.navy, fontSize: 7, fontFamily: "Helvetica-Bold", textAlign: "right" },
});

export const chartColors = ["#102a4b", "#2f8f9d", "#c9a84c", "#6b7f99", "#8c5e58", "#5b8c71"];
