/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevelopersIndexRouteImport } from './routes/developers.index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as BillingCancelRouteImport } from './routes/billing.cancel'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminPlatformRouteImport } from './routes/_authenticated/admin_.platform'
import { Route as ProjectsSlugUnitsUnitTypeIdRouteImport } from './routes/projects.$slug.units.$unitTypeId'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin_.projects.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPlatformRoute =
  AuthenticatedAdminPlatformRouteImport.update({
    id: '/admin_/platform',
    path: '/admin/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProjectsSlugUnitsUnitTypeIdRoute =
  ProjectsSlugUnitsUnitTypeIdRouteImport.update({
    id: '/units/$unitTypeId',
    path: '/units/$unitTypeId',
    getParentRoute: () => ProjectsSlugRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/admin_/projects/$id',
    path: '/admin/projects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/billing/': typeof BillingIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/projects/$slug/units/$unitTypeId': typeof ProjectsSlugUnitsUnitTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/billing': typeof BillingIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/developers': typeof DevelopersIndexRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/projects/$slug/units/$unitTypeId': typeof ProjectsSlugUnitsUnitTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/billing/': typeof BillingIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/_authenticated/admin_/platform': typeof AuthenticatedAdminPlatformRoute
  '/_authenticated/admin_/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/projects/$slug/units/$unitTypeId': typeof ProjectsSlugUnitsUnitTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/signup'
    | '/admin'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$slug'
    | '/billing/'
    | '/communities/'
    | '/developers/'
    | '/admin/platform'
    | '/admin/projects/$id'
    | '/projects/$slug/units/$unitTypeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/signup'
    | '/admin'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$slug'
    | '/billing'
    | '/communities'
    | '/developers'
    | '/admin/platform'
    | '/admin/projects/$id'
    | '/projects/$slug/units/$unitTypeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/signup'
    | '/_authenticated/admin'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$slug'
    | '/billing/'
    | '/communities/'
    | '/developers/'
    | '/_authenticated/admin_/platform'
    | '/_authenticated/admin_/projects/$id'
    | '/projects/$slug/units/$unitTypeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignupRoute: typeof SignupRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  BillingIndexRoute: typeof BillingIndexRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/': {
      id: '/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/platform': {
      id: '/_authenticated/admin_/platform'
      path: '/admin/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AuthenticatedAdminPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projects/$slug/units/$unitTypeId': {
      id: '/projects/$slug/units/$unitTypeId'
      path: '/units/$unitTypeId'
      fullPath: '/projects/$slug/units/$unitTypeId'
      preLoaderRoute: typeof ProjectsSlugUnitsUnitTypeIdRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/_authenticated/admin_/projects/$id': {
      id: '/_authenticated/admin_/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminPlatformRoute: typeof AuthenticatedAdminPlatformRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminPlatformRoute: AuthenticatedAdminPlatformRoute,
  AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProjectsSlugRouteChildren {
  ProjectsSlugUnitsUnitTypeIdRoute: typeof ProjectsSlugUnitsUnitTypeIdRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugUnitsUnitTypeIdRoute: ProjectsSlugUnitsUnitTypeIdRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SignupRoute: SignupRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  BillingIndexRoute: BillingIndexRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
