/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevelopersIndexRouteImport } from './routes/developers.index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as BillingCancelRouteImport } from './routes/billing.cancel'
import { Route as ApiRetentionRouteImport } from './routes/api.retention'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminPlatformRouteImport } from './routes/_authenticated/admin_.platform'
import { Route as AuthenticatedAdminActivityLogRouteImport } from './routes/_authenticated/admin_.activity-log'
import { Route as ProjectsSlugTourTourIdRouteImport } from './routes/projects_.$slug.tour.$tourId'
import { Route as ProjectsSlugUnitsUnitTypeIdRouteImport } from './routes/projects.$slug.units.$unitTypeId'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin_.projects.$id'
import { Route as ProjectsSlugTourTourIdIndexRouteImport } from './routes/projects_.$slug.tour.$tourId.index'
import { Route as AuthenticatedAdminProjectsIdToursRouteImport } from './routes/_authenticated/admin_.projects.$id_.tours'
import { Route as ProjectsSlugTourTourIdSceneSceneIdRouteImport } from './routes/projects_.$slug.tour.$tourId.scene.$sceneId'
import { Route as AuthenticatedAdminProjectsIdToursTourIdRouteImport } from './routes/_authenticated/admin_.projects.$id_.tours_.$tourId'
import { Route as AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRouteImport } from './routes/_authenticated/admin_.projects.$id_.tours_.$tourId_.floors_.$floorId_.editor'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersIndexRoute = DevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelRoute = BillingCancelRouteImport.update({
  id: '/billing/cancel',
  path: '/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRetentionRoute = ApiRetentionRouteImport.update({
  id: '/api/retention',
  path: '/api/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPlatformRoute =
  AuthenticatedAdminPlatformRouteImport.update({
    id: '/admin_/platform',
    path: '/admin/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivityLogRoute =
  AuthenticatedAdminActivityLogRouteImport.update({
    id: '/admin_/activity-log',
    path: '/admin/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProjectsSlugTourTourIdRoute = ProjectsSlugTourTourIdRouteImport.update({
  id: '/projects_/$slug/tour/$tourId',
  path: '/projects/$slug/tour/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugUnitsUnitTypeIdRoute =
  ProjectsSlugUnitsUnitTypeIdRouteImport.update({
    id: '/units/$unitTypeId',
    path: '/units/$unitTypeId',
    getParentRoute: () => ProjectsSlugRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/admin_/projects/$id',
    path: '/admin/projects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProjectsSlugTourTourIdIndexRoute =
  ProjectsSlugTourTourIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsSlugTourTourIdRoute,
  } as any)
const AuthenticatedAdminProjectsIdToursRoute =
  AuthenticatedAdminProjectsIdToursRouteImport.update({
    id: '/admin_/projects/$id_/tours',
    path: '/admin/projects/$id/tours',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProjectsSlugTourTourIdSceneSceneIdRoute =
  ProjectsSlugTourTourIdSceneSceneIdRouteImport.update({
    id: '/scene/$sceneId',
    path: '/scene/$sceneId',
    getParentRoute: () => ProjectsSlugTourTourIdRoute,
  } as any)
const AuthenticatedAdminProjectsIdToursTourIdRoute =
  AuthenticatedAdminProjectsIdToursTourIdRouteImport.update({
    id: '/admin_/projects/$id_/tours_/$tourId',
    path: '/admin/projects/$id/tours/$tourId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute =
  AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRouteImport.update({
    id: '/admin_/projects/$id_/tours_/$tourId_/floors_/$floorId_/editor',
    path: '/admin/projects/$id/tours/$tourId/floors/$floorId/editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/retention': typeof ApiRetentionRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/billing/': typeof BillingIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/projects/$slug/units/$unitTypeId': typeof ProjectsSlugUnitsUnitTypeIdRoute
  '/projects/$slug/tour/$tourId': typeof ProjectsSlugTourTourIdRouteWithChildren
  '/admin/projects/$id/tours': typeof AuthenticatedAdminProjectsIdToursRoute
  '/projects/$slug/tour/$tourId/': typeof ProjectsSlugTourTourIdIndexRoute
  '/admin/projects/$id/tours/$tourId': typeof AuthenticatedAdminProjectsIdToursTourIdRoute
  '/projects/$slug/tour/$tourId/scene/$sceneId': typeof ProjectsSlugTourTourIdSceneSceneIdRoute
  '/admin/projects/$id/tours/$tourId/floors/$floorId/editor': typeof AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/retention': typeof ApiRetentionRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/billing': typeof BillingIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/developers': typeof DevelopersIndexRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/projects/$slug/units/$unitTypeId': typeof ProjectsSlugUnitsUnitTypeIdRoute
  '/admin/projects/$id/tours': typeof AuthenticatedAdminProjectsIdToursRoute
  '/projects/$slug/tour/$tourId': typeof ProjectsSlugTourTourIdIndexRoute
  '/admin/projects/$id/tours/$tourId': typeof AuthenticatedAdminProjectsIdToursTourIdRoute
  '/projects/$slug/tour/$tourId/scene/$sceneId': typeof ProjectsSlugTourTourIdSceneSceneIdRoute
  '/admin/projects/$id/tours/$tourId/floors/$floorId/editor': typeof AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/retention': typeof ApiRetentionRoute
  '/billing/cancel': typeof BillingCancelRoute
  '/billing/success': typeof BillingSuccessRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/billing/': typeof BillingIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/developers/': typeof DevelopersIndexRoute
  '/_authenticated/admin_/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/_authenticated/admin_/platform': typeof AuthenticatedAdminPlatformRoute
  '/_authenticated/admin_/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/projects/$slug/units/$unitTypeId': typeof ProjectsSlugUnitsUnitTypeIdRoute
  '/projects_/$slug/tour/$tourId': typeof ProjectsSlugTourTourIdRouteWithChildren
  '/_authenticated/admin_/projects/$id_/tours': typeof AuthenticatedAdminProjectsIdToursRoute
  '/projects_/$slug/tour/$tourId/': typeof ProjectsSlugTourTourIdIndexRoute
  '/_authenticated/admin_/projects/$id_/tours_/$tourId': typeof AuthenticatedAdminProjectsIdToursTourIdRoute
  '/projects_/$slug/tour/$tourId/scene/$sceneId': typeof ProjectsSlugTourTourIdSceneSceneIdRoute
  '/_authenticated/admin_/projects/$id_/tours_/$tourId_/floors_/$floorId_/editor': typeof AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/signup'
    | '/admin'
    | '/api/retention'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$slug'
    | '/billing/'
    | '/communities/'
    | '/developers/'
    | '/admin/activity-log'
    | '/admin/platform'
    | '/admin/projects/$id'
    | '/projects/$slug/units/$unitTypeId'
    | '/projects/$slug/tour/$tourId'
    | '/admin/projects/$id/tours'
    | '/projects/$slug/tour/$tourId/'
    | '/admin/projects/$id/tours/$tourId'
    | '/projects/$slug/tour/$tourId/scene/$sceneId'
    | '/admin/projects/$id/tours/$tourId/floors/$floorId/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/signup'
    | '/admin'
    | '/api/retention'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$slug'
    | '/billing'
    | '/communities'
    | '/developers'
    | '/admin/activity-log'
    | '/admin/platform'
    | '/admin/projects/$id'
    | '/projects/$slug/units/$unitTypeId'
    | '/admin/projects/$id/tours'
    | '/projects/$slug/tour/$tourId'
    | '/admin/projects/$id/tours/$tourId'
    | '/projects/$slug/tour/$tourId/scene/$sceneId'
    | '/admin/projects/$id/tours/$tourId/floors/$floorId/editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/signup'
    | '/_authenticated/admin'
    | '/api/retention'
    | '/billing/cancel'
    | '/billing/success'
    | '/projects/$slug'
    | '/billing/'
    | '/communities/'
    | '/developers/'
    | '/_authenticated/admin_/activity-log'
    | '/_authenticated/admin_/platform'
    | '/_authenticated/admin_/projects/$id'
    | '/projects/$slug/units/$unitTypeId'
    | '/projects_/$slug/tour/$tourId'
    | '/_authenticated/admin_/projects/$id_/tours'
    | '/projects_/$slug/tour/$tourId/'
    | '/_authenticated/admin_/projects/$id_/tours_/$tourId'
    | '/projects_/$slug/tour/$tourId/scene/$sceneId'
    | '/_authenticated/admin_/projects/$id_/tours_/$tourId_/floors_/$floorId_/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignupRoute: typeof SignupRoute
  ApiRetentionRoute: typeof ApiRetentionRoute
  BillingCancelRoute: typeof BillingCancelRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  BillingIndexRoute: typeof BillingIndexRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  DevelopersIndexRoute: typeof DevelopersIndexRoute
  ProjectsSlugTourTourIdRoute: typeof ProjectsSlugTourTourIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/': {
      id: '/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof DevelopersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/cancel': {
      id: '/billing/cancel'
      path: '/billing/cancel'
      fullPath: '/billing/cancel'
      preLoaderRoute: typeof BillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retention': {
      id: '/api/retention'
      path: '/api/retention'
      fullPath: '/api/retention'
      preLoaderRoute: typeof ApiRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/platform': {
      id: '/_authenticated/admin_/platform'
      path: '/admin/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AuthenticatedAdminPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/activity-log': {
      id: '/_authenticated/admin_/activity-log'
      path: '/admin/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projects_/$slug/tour/$tourId': {
      id: '/projects_/$slug/tour/$tourId'
      path: '/projects/$slug/tour/$tourId'
      fullPath: '/projects/$slug/tour/$tourId'
      preLoaderRoute: typeof ProjectsSlugTourTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/units/$unitTypeId': {
      id: '/projects/$slug/units/$unitTypeId'
      path: '/units/$unitTypeId'
      fullPath: '/projects/$slug/units/$unitTypeId'
      preLoaderRoute: typeof ProjectsSlugUnitsUnitTypeIdRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/_authenticated/admin_/projects/$id': {
      id: '/_authenticated/admin_/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projects_/$slug/tour/$tourId/': {
      id: '/projects_/$slug/tour/$tourId/'
      path: '/'
      fullPath: '/projects/$slug/tour/$tourId/'
      preLoaderRoute: typeof ProjectsSlugTourTourIdIndexRouteImport
      parentRoute: typeof ProjectsSlugTourTourIdRoute
    }
    '/_authenticated/admin_/projects/$id_/tours': {
      id: '/_authenticated/admin_/projects/$id_/tours'
      path: '/admin/projects/$id/tours'
      fullPath: '/admin/projects/$id/tours'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdToursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/projects_/$slug/tour/$tourId/scene/$sceneId': {
      id: '/projects_/$slug/tour/$tourId/scene/$sceneId'
      path: '/scene/$sceneId'
      fullPath: '/projects/$slug/tour/$tourId/scene/$sceneId'
      preLoaderRoute: typeof ProjectsSlugTourTourIdSceneSceneIdRouteImport
      parentRoute: typeof ProjectsSlugTourTourIdRoute
    }
    '/_authenticated/admin_/projects/$id_/tours_/$tourId': {
      id: '/_authenticated/admin_/projects/$id_/tours_/$tourId'
      path: '/admin/projects/$id/tours/$tourId'
      fullPath: '/admin/projects/$id/tours/$tourId'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdToursTourIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/projects/$id_/tours_/$tourId_/floors_/$floorId_/editor': {
      id: '/_authenticated/admin_/projects/$id_/tours_/$tourId_/floors_/$floorId_/editor'
      path: '/admin/projects/$id/tours/$tourId/floors/$floorId/editor'
      fullPath: '/admin/projects/$id/tours/$tourId/floors/$floorId/editor'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminActivityLogRoute: typeof AuthenticatedAdminActivityLogRoute
  AuthenticatedAdminPlatformRoute: typeof AuthenticatedAdminPlatformRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminProjectsIdToursRoute: typeof AuthenticatedAdminProjectsIdToursRoute
  AuthenticatedAdminProjectsIdToursTourIdRoute: typeof AuthenticatedAdminProjectsIdToursTourIdRoute
  AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute: typeof AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminActivityLogRoute: AuthenticatedAdminActivityLogRoute,
  AuthenticatedAdminPlatformRoute: AuthenticatedAdminPlatformRoute,
  AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
  AuthenticatedAdminProjectsIdToursRoute:
    AuthenticatedAdminProjectsIdToursRoute,
  AuthenticatedAdminProjectsIdToursTourIdRoute:
    AuthenticatedAdminProjectsIdToursTourIdRoute,
  AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute:
    AuthenticatedAdminProjectsIdToursTourIdFloorsFloorIdEditorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProjectsSlugRouteChildren {
  ProjectsSlugUnitsUnitTypeIdRoute: typeof ProjectsSlugUnitsUnitTypeIdRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugUnitsUnitTypeIdRoute: ProjectsSlugUnitsUnitTypeIdRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

interface ProjectsSlugTourTourIdRouteChildren {
  ProjectsSlugTourTourIdIndexRoute: typeof ProjectsSlugTourTourIdIndexRoute
  ProjectsSlugTourTourIdSceneSceneIdRoute: typeof ProjectsSlugTourTourIdSceneSceneIdRoute
}

const ProjectsSlugTourTourIdRouteChildren: ProjectsSlugTourTourIdRouteChildren =
  {
    ProjectsSlugTourTourIdIndexRoute: ProjectsSlugTourTourIdIndexRoute,
    ProjectsSlugTourTourIdSceneSceneIdRoute:
      ProjectsSlugTourTourIdSceneSceneIdRoute,
  }

const ProjectsSlugTourTourIdRouteWithChildren =
  ProjectsSlugTourTourIdRoute._addFileChildren(
    ProjectsSlugTourTourIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SignupRoute: SignupRoute,
  ApiRetentionRoute: ApiRetentionRoute,
  BillingCancelRoute: BillingCancelRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  BillingIndexRoute: BillingIndexRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  DevelopersIndexRoute: DevelopersIndexRoute,
  ProjectsSlugTourTourIdRoute: ProjectsSlugTourTourIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
