export const MASTERPLAN_THEME = {
  land: "#c9ad78",
  sand: "#b9935b",
  water: "#0d8798",
  waterBlend: "#49c6c2",
  park: "#728f70",
  buildingResidential: "#efe4cf",
  buildingCommercial: "#9eafb6",
  buildingLandmark: "#7896a3",
  buildingHotel: "#dfc58f",
  buildingUnknown: "#d9d0bf",
  roadMotorway: "#292f34",
  roadTrunk: "#3b4248",
  roadPrimary: "#555d62",
  roadSecondary: "#767d7d",
  roadTertiary: "#999b96",
  roadLocal: "#b9b3a7",
  roadService: "#c9c0b0",
  roadCasing: "#eee3cf",
  roadCenterLine: "#d8ad55",
  roadBridge: "#242b30",
  roadBridgeCasing: "#c9a24f",
  roadBridgeShadow: "#10282b",
  roadTunnel: "#77756f",
  projectBoundary: "#b98a31",
  selected: "#f2bd51",
  hovered: "#ffe2a0",
  goldAccent: "#c9a84c",
  label: "#102729",
  labelOutline: "#f5f0e4",
  sky: "#b9d5dd",
} as const;

/** Rendering values shared by the masterplan layers. Keep visual tuning here. */
export const MASTERPLAN_VISUALS = {
  water: {
    frequency: 850,
    animationSpeed: 0.006,
    amplitude: 1.25,
    specularIntensity: 0.42,
    fadeFactor: 1.35,
  },
  roads: {
    casingExtraWidthPx: 2.2,
    bridgeCasingExtraWidthPx: 3.8,
    bridgeShadowExtraWidthPx: 6,
    bridgeShadowDropM: 1.5,
    centerLineWidthPx: 1,
  },
  scene: {
    desktopMaximumScreenSpaceError: 2,
    mobileMaximumScreenSpaceError: 3.5,
    desktopTileCacheSize: 180,
    mobileTileCacheSize: 90,
    fogDensity: 0.00018,
  },
} as const;

export const MASTERPLAN_LAYOUT = {
  defaultFloorHeightM: 3.2,
  minimumBuildingHeightM: 3,
  maximumBuildingHeightM: 900,
  fallbackHeightByTypeM: {
    residential: 15,
    apartments: 24,
    commercial: 20,
    hotel: 28,
    industrial: 9,
    retail: 8,
    unknown: 12,
  },
  bridgeBaseClearanceM: 7,
  bridgeLayerStepM: 6,
  roadGroundOffsetM: 0.35,
  waterOffsetM: 0.15,
  projectNearDistanceM: 65_000,
  projectFarDistanceM: 500_000,
} as const;

export type MasterplanTheme = typeof MASTERPLAN_THEME;
